ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from ecommerce import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from django.urls import path
from django.conf.urls.static import static
from shop import views
from .views import *

app_name = "shop"

urlpatterns = [
                  path('', views.home, name="home"),
                  path('signup/', views.signup, name="signup"),
                  path('signin/', views.signin, name="signin"),
                  path('signout/', views.signout, name="signout"),
                  path('search/', views.search, name="search"),
                  path('<slug>/', views.detail, name="detail"),
                  path('categories/<slug>/', views.categories, name="categories"),
                  path('shop/product/add/', views.product_add, name='product_add'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.conf import settings


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to="categories", blank=True)
    description = models.TextField(blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Product(models.Model):
    name = models.CharField(max_length=250)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to='media/product', blank=True)
    description = models.TextField(blank=True)
    phone = models.CharField(max_length=10, blank=True)
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models
from .models import Product


class PostForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'image', 'description', 'phone', 'price', 'category')
        image = forms.ImageField()


class SigninForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

shop/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from .forms import PostForm

# Create your views here.

from shop.forms import SignupForm, SigninForm
from shop.models import Product, Category
from shop.serializer import ProductSerializer


def home(request):
    products = Product.objects.filter(active=True)
    categories = Category.objects.filter(active=True)
    context = {"products": products, "categories": categories}
    return render(request, "shop/home.html", context)


def product_add(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.model_pic = form.cleaned_data['image']
            post.save()
            return redirect('/', pk=post.pk)

    elif request.user.is_authenticated:
        form = PostForm()
        return render(request, 'shop/post_edit.html', {'form': form})
    else:
        return render(request, 'shop/error.html')


def search(request):
    q = request.GET["q"]
    products = Product.objects.filter(active=True, name__icontains=q)
    categories = Category.objects.filter(active=True)
    context = {"products": products,
               "categories": categories,
               "title": q + " - search"}
    return render(request, "shop/list.html", context)


def categories(request, slug):
    cat = Category.objects.get(slug=slug)
    products = Product.objects.filter(active=True, category=cat)
    categories = Category.objects.filter(active=True)
    context = {"products": products, "categories": categories, "title": cat.name + " - Categories"}
    return render(request, "shop/list.html", context)


def detail(request, slug):
    product = Product.objects.get(active=True, slug=slug)

    categories = Category.objects.filter(active=True)
    context = {"product": product,
               "categories": categories,
               }
    return render(request, "shop/detail.html", context)


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            messages.success(request, "User saved")
            return redirect("shop:signin")
        else:
            messages.error(request, "Error in form")
    else:
        form = SignupForm()
    context = {"form": form}
    return render(request, "shop/signup.html", context)


def signin(request):
    if request.method == "POST":
        form = SigninForm(request.POST)
        # username = req.POST["username"]
        # password = req.POST["password"]
        username = form["username"].value()
        password = form["password"].value()
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully logged in")
            return redirect("shop:home")
        else:
            messages.error(request, "Invalid Username or Password")
    else:
        form = SigninForm()
    context = {"form": form}
    return render(request, "shop/signin.html", context)


def signout(request):
    logout(request)
    return redirect("shop:signin")

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load bootstrap4 %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/png" href="{% static "shop/media/favicon.jpg" %}"/>

    <title>{% block title %}Earphones {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "shop/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "shop/css/shop-homepage.css" %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
                    <a class="navbar-brand" href="/">Avai's Earphones Stock</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url "shop:home" %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>

              <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Account</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url "shop:signout" %}">Sign Out</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url "shop:signin" %}">Sign In</a>
                            <a class="dropdown-item" href="{% url "shop:signup" %}">Signup</a>
                        {% endif %}



                    </div>
                </li>
          </ul>

            <form class="form-inline my-2 my-lg-0 mr-4" action="{% url 'shop:search' %}">
                <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
            </form>

        </div>
 <a href= "{% url "shop:product_add" %}" class="btn btn-success"> Create New AD</a>
      </div>

                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="/"> Hello, {{user.get_username}}!</a>
                {% else %}
                    <a class="navbar-brand" href="/"> You are not logged in</a>
                {% endif %}
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">

          <h1 class="my-4">Categories</h1>
          <div class="list-group">
              {% for c in categories %}
                  <a href="{% url "shop:categories" c.slug %}" class="list-group-item">{{ c.name }}</a>
              {% endfor %}

          </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9 mt-3">
            {% bootstrap_messages %}
            {% block header %}
            {% endblock %}
                {% block content %}
                    <!-- /.row -->
            {% endblock %}

        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">&copy; Earphones E-commerce</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "shop/js/jquery.min.js" %}" type="text/javascript"></script>
    <script src="{% static "shop/js/bootstrap.min.js" %}" type="text/javascript"></script>

  </body>

</html>

shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% block title %} Ecommerce Home Page{% endblock  %}
{% load bootstrap4 %}
{% block content %}

    <div class="row">
        <div class="col-md-8">
          <img class="img-fluid" src="/media/{{ product.image }}" alt="{{ product.name|title }}">
        </div>

        <div class="col-md-4">
          <h1 class="my-3">{{ product.name|title }}</h1>
          <p>{{ product.description }}</p>
          <h5>Price: ${{ product.price|floatformat:"2" }}</h5>
          <h4>Phone: {{ product.phone }}</h4>
        </div>
</div>
        <hr>
        <div class="row">
        {% for item in product.review_set.all %}

        {% endfor %}
        </div>
    <div class="row mb-5">

    </div>
{% endblock %}

shop/templates/shop/error.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load bootstrap4 %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/png" href="{% static "shop/media/favicon.jpg" %}"/>

    <title>{% block title %}Earphones{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "shop/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "shop/css/shop-homepage.css" %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">Avai's Earphones Stock</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url "shop:home" %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>

              <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Account</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url "shop:signout" %}">Sign Out</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url "shop:signin" %}">Sign In</a>
                            <a class="dropdown-item" href="{% url "shop:signup" %}">Signup</a>
                        {% endif %}

                    </div>
                </li>
          </ul>

            <form class="form-inline my-2 my-lg-0 mr-4" action="{% url 'shop:search' %}">
                <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
      </div>
    </nav>
    <div class="container-fluid">



        <div class="row">
             <div class="col-md-4 mt-20">
                 <p>.</p>
            <h1>You should SIGN UP to add your own ADs</h1>

            <a class="btn btn-success" href="{% url "shop:signup" %}">Signup</a>


          </div>
 <div class="col-md-8 mt-8">
    <div class="col-sm-10 form-group-lg">
          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block img-fluid" src="https://shawnritzenthaler.com/wp-content/uploads/2018/10/shure-wireless-earphone-story-05.jpg" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="https://www.dafont.com/forum/attach/orig/5/2/529520.jpg" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="https://media3.webcollage.net/a769362cdf6c1477a025aaaebcb621bf24f1d07b?response-content-type=image%2Fjpeg&AWSAccessKeyId=AKIAIIE5CHZ4PRWSLYKQ&Expires=1893523572&Signature=Rfveq3z6O89V9Jj%2BTV%2FdIp4SxTo%3D" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
    </div>
 </div>
        </div>
         </div>
 <footer class="mt-9 py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">&copy; Earphones E-commerce</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "shop/js/jquery.min.js" %}" type="text/javascript"></script>
    <script src="{% static "shop/js/bootstrap.min.js" %}" type="text/javascript"></script>

  </body>

</html>

shop/templates/shop/home.html
{% extends "shop/base.html" %}
{% block title %}Earphones{% endblock  %}

{% block content %}
    <div class="row">
{% for item in products %}
    <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="{% url "shop:detail" item.slug %}"><img class="card-img-top" src="/media/{{ item.image}}" alt="{{ item.name }}"></a>
                    <div class="card-body">
                      <h3 class="card-title">
                        <a href="{% url "shop:detail" item.slug %}">{{ item.name|title }}</a>
                      </h3>
                      <h4>Phone: {{ item.phone }}</h4>
                      <h6>Price: ${{ item.price|floatformat:"2" }}</h6>

                      <p class="card-text">{{ item.description }}</p>
                    </div>
              </div>
    </div>
{% endfor %}
</div>
{% endblock %}


{% block header %}


          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block img-fluid" src="https://shawnritzenthaler.com/wp-content/uploads/2018/10/shure-wireless-earphone-story-05.jpg" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="https://www.dafont.com/forum/attach/orig/5/2/529520.jpg" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="https://media3.webcollage.net/a769362cdf6c1477a025aaaebcb621bf24f1d07b?response-content-type=image%2Fjpeg&AWSAccessKeyId=AKIAIIE5CHZ4PRWSLYKQ&Expires=1893523572&Signature=Rfveq3z6O89V9Jj%2BTV%2FdIp4SxTo%3D" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
{% endblock %}

shop/templates/shop/list.html
{% extends "shop/base.html" %}
{% block title %}{{ title }}{% endblock  %}

{% block content %}
    <div class="row">
{% for item in products %}
    <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="/media/{{ item.image }}" alt="A Pic"></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="{% url "shop:detail" item.slug %}">{{ item.name|title }}</a>
                  </h4>
                  <h5>Price: ${{ item.price|floatformat:"2" }}</h5>
                  <h4>Phone:{{ item.phone }}</h4>

                  <p class="card-text">{{ item.description }}</p>
                </div>

              </div>
            </div>
{% empty %}

{% endfor %}
    </div>

{% endblock %}

shop/templates/shop/post_edit.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load bootstrap4 %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/png" href="{% static "shop/media/favicon.jpg" %}"/>

    <title>{% block title %}Earphones NOW{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "shop/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "shop/css/shop-homepage.css" %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">Avai's Earphones Stock</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url "shop:home" %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>

              <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Account</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url "shop:signout" %}">Sign Out</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url "shop:signin" %}">Sign In</a>
                            <a class="dropdown-item" href="{% url "shop:signup" %}">Signup</a>
                        {% endif %}

                    </div>
                </li>
          </ul>

            <form class="form-inline my-2 my-lg-0 mr-4" action="{% url 'shop:search' %}">
                <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
      </div>
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="/"> Hello, {{user.get_username}}!</a>
                {% else %}
                    <a class="navbar-brand" href="/"> You are not logged in</a>
                {% endif %}
    </nav>
        <div class="row">
             <div class="col-lg-3">



          </div>
 <div class="col-lg-9 mt-3">
    <div class="col-sm-6 form-group-lg">
        <h2>New Earphones</h2>
            <form action="{% url 'shop:product_add' %}" method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Save</button>
            </form>
    </div>
 </div>
        </div>
 <footer class="mt-3 py-3 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">&copy; Earphones E-commerce</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "shop/js/jquery.min.js" %}" type="text/javascript"></script>
    <script src="{% static "shop/js/bootstrap.min.js" %}" type="text/javascript"></script>

  </body>

</html>

shop/templates/shop/signin.html
{#{% extends "blogs/base.html" %}#}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}


<title>{% block title %}Login{% endblock %}</title>


<div class="container">
    {% bootstrap_messages %}
    <div class="row">
        <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-header text-center">
                    Login
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    {#    {{ form.as_p }}#}
                        <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Sign In">
                        <a href="{% url "shop:signup" %}" class="small">Sign Up</a>
                        <a href="/" class="float-right small">Home</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


</div>

shop/templates/shop/signup.html
{#{% extends "blogs/base.html" %}#}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<title>{% block title %}SignUp {% endblock %}</title>

<div class="container">
    {% bootstrap_messages %}
    <div class="row">
        <div class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-header text-center">
                    Sign Up
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    {#    {{ form.as_p }}#}
                        <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Sign Up">
                        <a href="{% url "shop:signin" %}" class="small">Sign In</a>
                        <a href="/" class="float-right small">Home</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>